event/urls.py
from django.urls import path

from event.views import (
    EventListView,
    EventDetailView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    RunnerListView,
    RunnerDetailView,
    RunnerUpdateView,
    RunnerDeleteView,
    EventRegistrationListView,
    RegistrationCreateView,
    RegistrationUpdateView,
    MyRegistrationsView,
    RunnerRegisterView,
    RegistrationDeleteView,
    ArchiveListView,
)

app_name = "event"

urlpatterns = [
    path("", EventListView.as_view(), name="index"),
    path(
        "events/<int:pk>/detail",
        EventDetailView.as_view(),
        name="event_detail"
    ),
    path("events/create", EventCreateView.as_view(), name="event_create"),
    path(
        "events/<int:pk>/update",
        EventUpdateView.as_view(),
        name="event_update"
    ),
    path(
        "events/<int:pk>/delete",
        EventDeleteView.as_view(),
        name="event_delete"
    ),
    path("register/", RunnerRegisterView.as_view(), name="register_runner"),
    path("runners/", RunnerListView.as_view(), name="runner_list"),
    path(
        "runners/<int:pk>/detail",
        RunnerDetailView.as_view(),
        name="runner_detail"
    ),
    path(
        "runners/<int:pk>/update",
        RunnerUpdateView.as_view(),
        name="runner_update"
    ),
    path(
        "runners/<int:pk>/delete",
        RunnerDeleteView.as_view(),
        name="runner_delete"
    ),
    path(
        "events/<int:pk>/registrations/",
        EventRegistrationListView.as_view(),
        name="registration_list",
    ),
    path(
        "my-registrations/",
        MyRegistrationsView.as_view(),
        name="my_registrations_list"
    ),
    path(
        "registrations/<int:event_id>/create/",
        RegistrationCreateView.as_view(),
        name="registration_create",
    ),
    path(
        "registrations/<int:pk>/update/",
        RegistrationUpdateView.as_view(),
        name="registration_update",
    ),
    path(
        "registrations/<int:pk>/delete/",
        RegistrationDeleteView.as_view(),
        name="registration_delete",
    ),
    path(
        "",
        RegistrationDeleteView.as_view(),
        name="registration_delete",
    ),
    path(
        "registrations/<int:pk>/delete/",
        RegistrationDeleteView.as_view(),
        name="registration_delete",
    ),
    path(
        "archive/",
        ArchiveListView.as_view(),
        name="archive_list",
    ),
]

runner_community/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("event.urls", namespace="events")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

event/models.py
from datetime import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


class Runner(AbstractUser):
    first_name = models.CharField(max_length=30, blank=False)
    last_name = models.CharField(max_length=30, blank=False)
    city = models.CharField(max_length=30)
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(
        max_length=10,
        choices=[
            ("Male", "Male"),
            ("Female", "Female"),
        ],
    )
    phone_number = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.last_name} {self.first_name}"

    def get_age(self) -> int:
        today = datetime.today()
        age = today.year - self.date_of_birth.year
        if today.month < self.date_of_birth.month or (
            today.month == self.date_of_birth.month and today.
                day < self.date_of_birth.day
        ):
            age -= 1
        return age


class Distance(models.Model):
    km = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.km} km"


class Event(models.Model):
    EVENT_TYPE_CHOICES = [
        ("Running", "Running"),
        ("Cycling", "Cycling"),
        ("Swimming", "Swimming"),
    ]

    name = models.CharField(max_length=100)
    start_datetime = models.DateTimeField()
    location = models.CharField(max_length=100)
    distances = models.ManyToManyField(Distance, related_name="events")
    description = models.TextField()
    event_type = models.CharField(max_length=100, choices=EVENT_TYPE_CHOICES)
    organiser = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ("start_datetime",)

    def get_distances(self) -> list[str]:
        return [distance.km for distance in self.distances.all()]

    def update_is_active_status(self) -> None:
        if self.start_datetime <= timezone.now():
            self.is_active = False
        else:
            self.is_active = True
        self.save()

    def save(self, *args: tuple, **kwargs: dict) -> None:
        if self.start_datetime <= timezone.now():
            self.is_active = False
        else:
            self.is_active = True
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Registration(models.Model):
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name="registrations"
    )
    runner = models.ForeignKey(
        Runner, on_delete=models.CASCADE, related_name="registrations"
    )
    registration_date = models.DateTimeField(auto_now_add=True)
    distances = models.ForeignKey(Distance, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

    def __str__(self) -> str:
        return (
            f"{self.runner.last_name} "
            f"{self.runner.first_name} - "
            f"{self.event.name}"
        )

event/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.utils import timezone
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.auth import update_session_auth_hash

from event.forms import (
    RunnerCreationForm,
    RunnerUpdateForm,
    EventCreationForm,
    EventSearchForm,
    RegistrationForm,
)
from event.models import Event, Runner, Registration, Distance
from django.urls import reverse_lazy, reverse


class BaseEventListView(LoginRequiredMixin, generic.ListView):
    model = Event
    context_object_name = "events"
    paginate_by = 7

    def get_queryset(self) -> Event:
        queryset = Event.objects.all()

        event_type = self.request.GET.get("event_type")
        if event_type:
            queryset = queryset.filter(event_type=event_type)

        form = EventSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get("name", "")
            location = form.cleaned_data.get("location", "")
            if name:
                queryset = queryset.filter(name__icontains=name)
            if location:
                queryset = queryset.filter(location__icontains=location)
        return queryset.filter(is_active=True)

    def get_context_data(self, **kwargs: dict) -> dict:
        context = super().get_context_data(**kwargs)
        context["search_form"] = EventSearchForm(self.request.GET)
        context["distances"] = Distance.objects.all()
        for event in context["events"]:
            event.registration_count = event.registrations.count()
        return context


class EventListView(BaseEventListView):
    template_name = "event/index.html"

    def get_queryset(self) -> Event:
        queryset = super().get_queryset()
        event_type = self.request.GET.get("event_type")
        if event_type:
            queryset = queryset.filter(event_type=event_type)
        return queryset.filter(
            start_datetime__gt=timezone.now(),
            is_active=True
        )

    def get_context_data(self, **kwargs: dict) -> dict:
        context = super().get_context_data(**kwargs)
        context["segment"] = "events"
        return context


class ArchiveListView(BaseEventListView):
    model = Event
    template_name = "event/archive_list.html"
    context_object_name = "events"

    def get_queryset(self):
        return Event.objects.filter(start_datetime__lt=timezone.now())

    def get_context_data(self, **kwargs: dict) -> dict:
        context = super().get_context_data(**kwargs)
        context["segment"] = "archive"
        return context


class EventDetailView(LoginRequiredMixin, generic.DetailView):
    model = Event
    context_object_name = "event"
    template_name = "event/event_detail.html"

    def get_context_data(self, **kwargs: dict) -> dict:
        context = super().get_context_data(**kwargs)
        context["runner"] = self.request.user
        return context


class EventCreateView(LoginRequiredMixin, generic.CreateView):
    model = Event
    form_class = EventCreationForm
    template_name = "event/event_form.html"
    success_url = reverse_lazy("event:index")


class EventUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Event
    form_class = EventCreationForm
    template_name = "event/event_form.html"
    success_url = reverse_lazy("event:index")


class EventDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Event
    template_name = "event/event_confirm_delete.html"
    success_url = reverse_lazy("event:index")


class RunnerListView(LoginRequiredMixin, generic.ListView):
    model = Runner
    context_object_name = "runners"
    template_name = "event/runner_list.html"
    ordering = ["last_name", "first_name"]


class RunnerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Runner
    context_object_name = "runner"
    template_name = "event/runner_detail.html"

    def get_context_data(self, **kwargs: dict) -> dict:
        context = super().get_context_data(**kwargs)
        runner = self.get_object()
        context["registrations"] = Registration.objects.filter(
            runner=runner).order_by("event__start_datetime")
        return context


class RunnerRegisterView(generic.CreateView):
    model = Runner
    form_class = RunnerCreationForm
    template_name = "event/runner_form.html"
    success_url = reverse_lazy("event:index")


class RunnerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Runner
    form_class = RunnerUpdateForm
    template_name = "event/runner_form.html"

    def get_success_url(self) -> str:
        runner = self.object
        return reverse("event:runner_detail", kwargs={"pk": runner.pk})

    def form_valid(self, form: EventCreationForm) -> HttpResponse:
        response = super().form_valid(form)
        update_session_auth_hash(self.request, self.object)
        return response


class RunnerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Runner
    template_name = "event/runner_confirm_delete.html"
    success_url = reverse_lazy("event:index")


class EventRegistrationListView(LoginRequiredMixin, generic.ListView):
    model = Registration
    template_name = "event/registration_list.html"
    context_object_name = "registrations"

    def get_queryset(self) -> Registration:
        event_id = self.kwargs["pk"]
        return Registration.objects.filter(
            event_id=event_id).order_by("distances")

    def get_context_data(self, **kwargs: dict) -> dict:
        context = super().get_context_data(**kwargs)
        event_id = self.kwargs["pk"]
        event = Event.objects.get(pk=event_id)

        context.update(
            {
                "event_type": event.event_type,
                "event_name": event.name,
                "event_date": event.start_datetime,
                "event_location": event.location,
                "distances": event.get_distances(),
                "organiser": event.organiser,
            }
        )
        return context


class MyRegistrationsView(LoginRequiredMixin, generic.ListView):
    model = Registration
    context_object_name = "registrations"
    template_name = "event/my-registration_list.html"

    def get_queryset(self) -> Registration:
        return Registration.objects.filter(runner=self.request.user)

    def get_context_data(self, **kwargs: dict) -> dict[Event]:
        context = super().get_context_data(**kwargs)
        context["runner"] = self.request.user
        context["events"] = Event.objects.filter(
            id__in=context["registrations"].values("event")
        )
        context["runner_id"] = context["runner"].pk
        return context


class RegistrationCreateView(LoginRequiredMixin, generic.CreateView):
    model = Registration
    form_class = RegistrationForm
    # template_name = "event/registration_form.html"

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        kwargs["event_id"] = self.kwargs["event_id"]
        return kwargs

    def form_valid(self, form: EventCreationForm) -> HttpResponse:
        event = get_object_or_404(Event, id=self.kwargs["event_id"])
        runner = self.request.user

        if Registration.objects.filter(event=event, runner=runner).exists():
            form.add_error(None, "You are already registered for this event.")
            return self.form_invalid(form)

        form.instance.event = event
        form.instance.runner = runner
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy("event:my_registrations_list")


class RegistrationUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Registration
    form_class = RegistrationForm
    template_name = "event/registration_form.html"

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        registration = self.get_object()
        kwargs["event_id"] = registration.event.id
        return kwargs

    def get_success_url(self) -> str:
        return reverse_lazy("event:my_registrations_list")


class RegistrationDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Registration
    template_name = "event/registration_confirm_delete.html"
    success_url = reverse_lazy("event:my_registrations_list")

templates/event/archive_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="Search" class="btn btn-primary" formnovalidate>
  </form>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Date race</th>
        <th>Name race</th>
        <th>Location</th>
        <th>Distances</th>
        <th>Organiser</th>
        <th>Participants</th>
      </tr>
    </thead>
    <tbody>
      {% for event in events %}
        <tr>
          <td>{{ event.start_datetime|date:"d.m.Y, l" }}</td>
          <td><a href="{% url 'event:event_detail' pk=event.id %}" class="btn btn-outline-gray-800 btn-custom-width">{{ event.name }}</a></td>
          <td>{{ event.location }}</td>
          <td>
            {% for distance in event.get_distances %}
              {{ distance }} km{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </td>
          <td>{{ event.organiser }}</td>
          <td class="td-participants">
            <a href="{% url 'event:registration_list' pk=event.id %}" class="btn btn-outline-gray-800">
              Participants: {{ event.registration_count }}
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/event/event_confirm_delete.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>Delete event</h1>
  <p>Are you sure you want to delete the event: {{ event }}?</p>
  <p><i>All Runners with this event will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" />
  </form>
  <a href="{% url 'event:index' pk=event.id %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

templates/event/event_detail.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>{{ event.name }}</h1>
  <p>{{ event.location }}</p>
  <br>
  <p><strong>Date: </strong>{{ event.start_datetime|date:"d.m.Y, l" }}</p>
  <p><strong>Time: </strong>{{ event.start_datetime|date:"H:i" }}</p>
  <p><strong>Description: </strong>{{ event.description|linebreaks }}</p>
  {% if runner == user or user.is_staff %}
    {% now "Y-m-d H:i:s" as current_time %}
    {% if event.start_datetime|date:"Y-m-d H:i:s" > current_time %}
      <td>
        <a href="{% url 'event:registration_create' event_id=event.id %}" class="btn btn-primary">registration</a>
      </td>
    {% else %}
      <h3>The event has passed</h3>
    {% endif %}
  {% endif %}
  {% if runner.is_staff %}
    <a href="{% url "event:event_update" pk=event.id %}" class="btn btn-primary mr-5">Update</a>
    <a href="{% url "event:event_delete" pk=event.id %}" class="btn btn-danger">Delete</a>
  {% endif %}
{% endblock %}

templates/event/event_form.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Event</h1>
  {% block form %}
    {% include "includes/form.html" %}
  {% endblock %}
{% endblock %}

templates/event/event_registration_list.html
{% extends "base.html" %}
{% block content %}
  <h1>My Event Registrations</h1>
  
  {% if user_events %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Event Name</th>
          <th>Date</th>
          <th>Location</th>
          <th>Description</th>
          <th>Distance</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {% for event in events %}
          <tr>
            <td>{{ event.name }}</td>
            <td>{{ event.date | date:"d.m.Y" }}</td>
            <td>{{ event.location }}</td>
            <td>{{ event.description }}</td>
            <td>
              {% for registration in event.events.all %}
                {% if registration.runner == user %}
                  {{ registration.distance }} {{ registration.get_distance_choices|first }}
                {% endif %}
              {% endfor %}
            </td>
            <td>
              {% for registration in event.events.all %}
                {% if registration.runner == user %}
                  {{ registration.get_status_display }}
                {% endif %}
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>You are not registered for any events.</p>
  {% endif %}
{% endblock %}

templates/event/index.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  
  {% if user.is_staff %}
    <div class="mb-3">
      <a href="{% url 'event:event_create' %}" class="btn btn-primary">Create New Event</a>
    </div>
  {% endif %}
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="Search" class="btn btn-primary" formnovalidate>
  </form>
  <br>
  <div class="table-container">
    <table class="table table-striped table-hover">
      <colgroup>
        <col class="col-date" style="width: 8%;">
        <col class="col-name" style="width: 30%;">
        <col class="col-location" style="width: 15%;">
        <col class="col-distances" style="width: 10%;">
        <col class="col-organiser" style="width: 8%;">
        <col class="col-participants" style="width: 10%;">
        <col class="col-registration" style="width: 8%;">
      </colgroup>
      <thead>
        <tr>
          <th class="th-date">Date race</th>
          <th class="th-name">Name race</th>
          <th class="th-location">Location</th>
          <th class="th-distances">Distances</th>
          <th class="th-organiser">Organiser</th>
          <th class="th-participants">Participants</th>
          {% if not user.is_staff %}
            <th class="th-registration">Registration</th>
          {% else %}
            <th class="th-registration">Update</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for event in events %}
          <tr>
            <td class="td-date">{{ event.start_datetime|date:"d.m.Y, l" }}</td>
            <td class="td-name">
              <a href="{% url 'event:event_detail' pk=event.id %}" class="btn btn-outline-gray-800 btn-custom-width">
                {{ event.name }}
              </a>
            </td>
            <td class="td-location">{{ event.location }}</td>
            <td class="td-distances">
              {% for distance in event.get_distances %}
                {{ distance }} km{% if not forloop.last %}, {% endif %}
              {% endfor %}
            </td>
            <td class="td-organiser">{{ event.organiser }}</td>
            <td class="td-participants">
              <a href="{% url 'event:registration_list' pk=event.id %}" class="btn btn-outline-gray-800">
                Participants: {{ event.registration_count }}
              </a>
            </td>
            {% if not user.is_staff %}
              <td class="td-registration">
                <a href="{% url 'event:registration_create' event_id=event.id %}" class="btn btn-outline-gray-800">
                  registration
                </a>
              </td>
            {% else %}
              <td class="td-update">
                <a href="{% url "event:event_update" pk=event.id %}" class="btn btn-outline-gray-800 mr-5">
                  Update
                </a>
              </td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/event/my-registration_list.html
{% extends "layouts/base.html" %}
{% block content %}
<h1>My registrations</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>№</th>
        <th>Date</th>
        <th>Name registration</th>
        <th>Distance</th>
        <th>Location</th>
        {% if runner == user or user.is_staff %}
          <th>Update</th>
          <th>Delete</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for registration in registrations %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ registration.event.start_datetime|date:"d.m.Y, H:i" }}</td>
          <td>
            <a href="{% url 'event:event_detail' pk=registration.event.pk %}" class="btn btn-outline-gray-800 btn-custom-width">
              {{ registration.event.name }}
            </a>
          </td>
          <td>{{ registration.distances }} км</td>
          <td>{{ registration.event.location }}</td>
          {% if runner == user or user.is_staff %}
            <th><a href="{% url 'event:registration_update' registration.id %}" class="btn btn-primary">Update</a></th>
            <th><a href="{% url 'event:registration_delete' registration.id %}" class="btn btn-danger">Delete</a></th>
          {% endif %}
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">You are not registered for any events.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/event/register_runner.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>Register Runner</h1>
  {% block form %}
    {% include "includes/form.html" %}
  {% endblock %}
{% endblock %}

templates/event/registration_confirm_delete.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>Delete registrations</h1>
  <p>Are you sure you want to delete the registration: {{ registration.event.name }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" >
  </form>
  <a href="{% url 'event:my_registrations_list' %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

templates/event/runner_confirm_delete.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>Delete runner</h1>
  <p>Are you sure you want to delete the runner: {{ runner }}?</p>
  <p><i>All Events with this runner will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" />
  </form>
  <a href="{% url 'event:runner_detail' pk=runner.id %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

templates/event/runner_detail.html
{% extends "layouts/base.html" %}

{% block content %}
  
  <h1>{{ runner.first_name }} {{ runner.last_name }}</h1>
  <div class="text-right mb-3">
    {% if runner == user or user.is_staff  %}
      <a href="{% url "event:runner_update" pk=runner.id %}" class="btn btn-primary mr-5">Update</a>
      <a href="{% url "event:runner_delete" pk=runner.id %}" class="btn btn-danger">Delete</a>
    {% endif %}
  </div>
  <p><strong>username: </strong>{{ runner.username }}</p>
  <p><strong>date of birth: </strong>{{ runner.date_of_birth|date:"d.m.Y" }}</p>
  {% if runner.phone_number %}
    <p><strong>Phone number: </strong>{{ runner.phone_number|phone2numeric }}</p>
  {% endif %}
  <h1>Registrations</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>№</th>
        <th>Date</th>
        <th>Name registration</th>
        <th>Distance</th>
        <th>Location</th>
      </tr>
    </thead>
    <tbody>
      {% for registration in registrations %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ registration.event.start_datetime|date:"d.m.Y, H:i" }}</td>
          <td><a href="{% url 'event:event_detail' pk=registration.event.pk %}">{{ registration.event.name }}</a></td>
          <td>{{ registration.distances }} км</td>
          <td>{{ registration.event.location }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">Not registered for any events.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

templates/event/runner_form.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} runner</h1>
  {% block form %}
    {% include "includes/form.html" %}
  {% endblock %}
{% endblock %}

templates/event/runner_list.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>All runners</h1>
  
  {% if runners %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Full name</th>
          <th>username</th>
          <th>Gender</th>
          <th>Date of birth:</th>
        </tr>
      </thead>
      <tbody>
        {% for runner in runners %}
          <tr>
          {% if not runner.is_staff %}
            <td>
              <a href="{% url 'event:runner_detail' pk=runner.id %}" class="btn btn-outline-gray-800 btn-custom-width">
                {{ runner.last_name }} {{ runner.first_name }}
              </a>
            </td>
            <td>{{ runner.username }}</td>
            <td>{{ runner.gender }}</td>
            <td>{{ runner.date_of_birth | date:"d.m.Y" }}</td>
          {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No one found</p>
  {% endif %}
{% endblock %}

templates/event/running-event_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  
  {% if user.is_staff %}
    <div class="mb-3">
      <a href="{% url 'event:event_create' %}" class="btn btn-primary">Create New Event</a>
    </div>
  {% endif %}
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="🧐" class="btn btn-secondary" formnovalidate>
  </form>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Date race</th>
        <th>Name race</th>
        <th>Location</th>
        <th>Distances</th>
        <th>Organiser</th>
        {% if not user.is_staff %}
          <th>Participants</th>
          <th>Registration</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for event in events %}
        {% if event.event_type == "Running" %}
        <tr>
          <td>{{ event.start_datetime|date:"d.m.Y, l" }}</td>
          <td><a href="{% url 'event:event_detail' pk=event.id %}">{{ event.name }}</a></td>
          <td>{{ event.location }}</td>
          <td>
            {% for distance in event.get_distances %}
              {{ distance }} km{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </td>
          <td>{{ event.organiser }}</td>
          <td><a href="{% url 'event:registration_list' pk=event.id %}" class="btn btn-secondary">participants</a></td>
          <td><a href="{% url 'event:registration_create' event_id=event.id %}" class="btn btn-primary">registration</a></td>
        </tr>
        {% endif %}
      {% endfor %}
    </tbody>
  </table>
{% endblock %}