event/urls.py
from django.urls import path

from event.views import (
    EventListView,
    EventDetailView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    RunnerListView,
    RunnerDetailView,
    RunnerUpdateView,
    RunnerDeleteView,
    EventRegistrationListView,
    RegistrationCreateView,
    RegistrationUpdateView,
    MyRegistrationsView,
    RunnerRegisterView,
    RegistrationDeleteView,
    ArchiveListView,
)

app_name = "event"

urlpatterns = [
    path("", EventListView.as_view(), name="index"),
    path(
        "events/<int:pk>/detail",
        EventDetailView.as_view(),
        name="event_detail"
    ),
    path("events/create", EventCreateView.as_view(), name="event_create"),
    path(
        "events/<int:pk>/update",
        EventUpdateView.as_view(),
        name="event_update"
    ),
    path(
        "events/<int:pk>/delete",
        EventDeleteView.as_view(),
        name="event_delete"
    ),
    path("register/", RunnerRegisterView.as_view(), name="register_runner"),
    path("runners/", RunnerListView.as_view(), name="runner_list"),
    path(
        "runners/<int:pk>/detail",
        RunnerDetailView.as_view(),
        name="runner_detail"
    ),
    path(
        "runners/<int:pk>/update",
        RunnerUpdateView.as_view(),
        name="runner_update"
    ),
    path(
        "runners/<int:pk>/delete",
        RunnerDeleteView.as_view(),
        name="runner_delete"
    ),
    path(
        "events/<int:pk>/registrations/",
        EventRegistrationListView.as_view(),
        name="registration_list",
    ),
    path(
        "my-registrations/",
        MyRegistrationsView.as_view(),
        name="my_registrations_list"
    ),
    path(
        "registrations/<int:event_id>/create/",
        RegistrationCreateView.as_view(),
        name="registration_create",
    ),
    path(
        "registrations/<int:pk>/update/",
        RegistrationUpdateView.as_view(),
        name="registration_update",
    ),
    path(
        "registrations/<int:pk>/delete/",
        RegistrationDeleteView.as_view(),
        name="registration_delete",
    ),
    path(
        "",
        RegistrationDeleteView.as_view(),
        name="registration_delete",
    ),
    path(
        "registrations/<int:pk>/delete/",
        RegistrationDeleteView.as_view(),
        name="registration_delete",
    ),
    path(
        "archive/",
        ArchiveListView.as_view(),
        name="archive_list",
    ),
]

runner_community/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("event.urls", namespace="events")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

templates/includes/form.html
{% load crispy_forms_filters %}
<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form | crispy }}
  <input class="btn btn-primary" type="submit" value="Submit">
</form>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
<!-- Core -->
<script src="{{ ASSETS_ROOT }}vendor/@popperjs/core/dist/umd/popper.min.js"></script>
<script src="{{ ASSETS_ROOT }}vendor/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Vendor JS -->
<script src="{{ ASSETS_ROOT }}vendor/onscreen/dist/on-screen.umd.min.js"></script>

<!-- Slider -->
<script src="{{ ASSETS_ROOT }}vendor/nouislider/distribute/nouislider.min.js"></script>

<!-- Smooth scroll -->
<script src="{{ ASSETS_ROOT }}vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

<!-- Charts -->
<script src="{{ ASSETS_ROOT }}vendor/chartist/dist/chartist.min.js"></script>
<script src="{{ ASSETS_ROOT }}vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>

<!-- Datepicker -->
<script src="{{ ASSETS_ROOT }}vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Sweet Alerts 2 -->
<script src="{{ ASSETS_ROOT }}vendor/sweetalert2/dist/sweetalert2.all.min.js"></script>

<!-- Vanilla JS Datepicker -->
<script src="{{ ASSETS_ROOT }}vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Notyf -->
<script src="{{ ASSETS_ROOT }}vendor/notyf/notyf.min.js"></script>

<!-- Simplebar -->
<script src="{{ ASSETS_ROOT }}vendor/simplebar/dist/simplebar.min.js"></script>

<!-- Volt JS -->
<script src="{{ ASSETS_ROOT }}js/volt.js"></script>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var sidebarToggleBtn = document.getElementById("sidebarToggle");
    var sidebar = document.getElementById("sidebarMenu");

    sidebarToggleBtn.addEventListener("click", function () {
      sidebar.classList.toggle("show"); // Перемикає видимість сайдбару
    });
  });
</script>

templates/includes/sidebar.html
<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
  <div class="sidebar-inner px-4 pt-3">
    <ul class="nav flex-column pt-3 pt-md-0">
      <li class="nav-item active">
        {% if user.is_authenticated %}
          <a href="{% url 'event:runner_detail' user.pk %}" class="nav-link">
            <span class="sidebar-text">
              Profile
              {% if user.is_staff %}
                admin
              {% endif %}
              {{ user.last_name }} {{ user.first_name }}
            </span>
          </a>
        {% endif %}
      </li>
      <li class="nav-item active">
        <a href="{% url 'event:runner_list' %}" class="nav-link">
          <span class="sidebar-icon">
              <svg class="icon icon-md me-2" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M14 13.41V22h-4v-8.59c-2.65-.5-4.68-2.88-4.68-5.81 0-3.31 2.69-6 6-6s6 2.69 6 6c0 2.93-2.03 5.31-4.68 5.81zM12 6c-2.21 0-4 1.79-4 4 0 2.21 1.79 4 4 4s4-1.79 4-4c0-2.21-1.79-4-4-4z"></path>
              </svg>
          </span>
          <span class="sidebar-text">Community</span>
        </a>
      </li>
      <li class="nav-item active">
        {% if user.registrations.exists %}
          <a href="{% url 'event:my_registrations_list' %}" class="nav-link">
            <span class="sidebar-icon">
                <svg class="icon icon-sm me-2" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 9a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 13a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                </svg>
            </span>
            <span class="sidebar-text">My registrations</span>
          </a>
        {% else %}
          <span>No registrations available</span>
        {% endif %}
      </li>

      <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>

      <li class="nav-item active">
        <span
          class="nav-link  collapsed  d-flex justify-content-between align-items-center"
          data-bs-toggle="collapse" data-bs-target="#submenu-app">
          <span>
            <span class="sidebar-icon">
              <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z" clip-rule="evenodd"></path></svg>
            </span>
            <span class="sidebar-text">Upcoming events</span>
          </span>
          <span class="link-arrow">
            <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
          </span>
        </span>
        <div class="multi-level collapse show"
          role="list" id="submenu-app" aria-expanded="false">
          <ul class="flex-column nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'event:index' %}?event_type=Running&is_active=True">
                <span class="sidebar-text">Running events</span>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'event:index' %}?event_type=Cycling&is_active=True">
                <span class="sidebar-text">Cycling events</span>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'event:index' %}?event_type=Swimming&is_active=True">
                <span class="sidebar-text">Swimming events</span>
              </a>
            </li>
          </ul>
        </div>
      </li>

      <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'event:archive_list'%}">
            <span class="sidebar-icon">
                <svg class="icon icon-sm me-2" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M7 3a1 1 0 011-1h4a1 1 0 011 1v2H7V3zm-2 3a1 1 0 011-1h10a1 1 0 011 1v10a1 1 0 01-1 1H6a1 1 0 01-1-1V6zm12 2H6v10h10V8z" clip-rule="evenodd"></path>
                </svg>
            </span>
            <span class="sidebar-text">Archive</span>
          </a>
      </li>

      <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
      {% if user.is_authenticated %}
        <li class="nav-item active">
          <form method="post" action="{% url 'logout' %}" class="d-flex align-items-center">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger btn-sm w-100 text-start">
              <span class="sidebar-icon">
                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path d="M16 17l4-4m0 0l-4-4m4 4H7"></path>
                </svg>
              </span>
              Logout
            </button>
          </form>
        </li>
      {% else %}
        <li class="nav-item active">
          <a href="{% url 'login' %}" class="btn btn-primary btn-sm">Login</a>
          <a href="{% url 'event:register_runner' %}" class="btn btn-primary">Register</a>
        </li>
    {% endif %}
    </ul>
  </div>
</nav>